# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/goghspr/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/goghspr/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/samsung/goghspr/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/goghspr/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/goghspr/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/goghspr/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/goghspr/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/samsung/goghspr/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/samsung/goghspr/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/goghspr/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/goghspr/proprietary/bin/sec-ril:system/bin/sec-ril \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.b05:system/etc/firmware/wcnss.b05 \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt \
    vendor/samsung/goghspr/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/goghspr/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/samsung/goghspr/proprietary/lib/hw/vendor-camera.msm8960.so:system/lib/hw/vendor-camera.msm8960.so \
    vendor/samsung/goghspr/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/samsung/goghspr/proprietary/lib/libaudioparsers.so:system/lib/libaudioparsers.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/samsung/goghspr/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/samsung/goghspr/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/samsung/goghspr/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/goghspr/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/samsung/goghspr/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/goghspr/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/goghspr/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/samsung/goghspr/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/goghspr/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so
