# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/goghspr/setup-makefiles.sh

LOCAL_PATH := vendor/samsung/goghsprspr

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/samsung/goghspr/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so

PRODUCT_COPY_FILES += \
    vendor/samsung/goghspr/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/samsung/goghspr/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/goghspr/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/samsung/goghspr/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/samsung/goghspr/proprietary/bin/ccid_daemon:system/bin/ccid_daemon \
    vendor/samsung/goghspr/proprietary/bin/cnd:system/bin/cnd \
    vendor/samsung/goghspr/proprietary/bin/connfwexe:system/bin/connfwexe \
    vendor/samsung/goghspr/proprietary/bin/curl:system/bin/curl \
    vendor/samsung/goghspr/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/samsung/goghspr/proprietary/bin/ddexe:system/bin/ddexe \
    vendor/samsung/goghspr/proprietary/bin/dttexe:system/bin/dttexe \
    vendor/samsung/goghspr/proprietary/bin/fmconfig:system/bin/fmconfig \
    vendor/samsung/goghspr/proprietary/bin/ftm_ptt:system/bin/ftm_ptt \
    vendor/samsung/goghspr/proprietary/bin/ftmdaemon:system/bin/ftmdaemon \
    vendor/samsung/goghspr/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/goghspr/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/goghspr/proprietary/bin/insthk:system/bin/insthk \
    vendor/samsung/goghspr/proprietary/bin/LE_dut:system/bin/LE_dut \
    vendor/samsung/goghspr/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/goghspr/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/samsung/goghspr/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/samsung/goghspr/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/samsung/goghspr/proprietary/bin/mtpd:system/bin/mtpd \
    vendor/samsung/goghspr/proprietary/bin/ndc:system/bin/ndc \
    vendor/samsung/goghspr/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/goghspr/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/samsung/goghspr/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/goghspr/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/samsung/goghspr/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/samsung/goghspr/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
    vendor/samsung/goghspr/proprietary/bin/qcom_audio_dut:system/bin/qcom_audio_dut \
    vendor/samsung/goghspr/proprietary/bin/qcom_dut:system/bin/qcom_dut \
    vendor/samsung/goghspr/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/samsung/goghspr/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/goghspr/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/samsung/goghspr/proprietary/bin/quipc_igsn:system/bin/quipc_igsn \
    vendor/samsung/goghspr/proprietary/bin/quipc_main:system/bin/quipc_main \
    vendor/samsung/goghspr/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/goghspr/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/goghspr/proprietary/bin/sapd:system/bin/sapd \
    vendor/samsung/goghspr/proprietary/bin/sec-ril:system/bin/sec-ril \
    vendor/samsung/goghspr/proprietary/bin/smdexe:system/bin/smdexe \
    vendor/samsung/goghspr/proprietary/bin/tc:system/bin/tc \
    vendor/samsung/goghspr/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/samsung/goghspr/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/samsung/goghspr/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/samsung/goghspr/proprietary/bin/wiperiface_v02:system/bin/wiperiface_v02 \
    vendor/samsung/goghspr/proprietary/bin/wlandutservice:system/bin/wlandutservice

PRODUCT_COPY_FILES += \
    vendor/samsung/goghspr/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw  \
    vendor/samsung/goghspr/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw  \
    vendor/samsung/goghspr/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw  \
    vendor/samsung/goghspr/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw  \
    vendor/samsung/goghspr/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw  \
    vendor/samsung/goghspr/proprietary/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex  \
    vendor/samsung/goghspr/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw  \
    vendor/samsung/goghspr/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/samsung/goghspr/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
    vendor/samsung/goghspr/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt  \
    vendor/samsung/goghspr/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat  \
    vendor/samsung/goghspr/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini

PRODUCT_COPY_FILES += \
    vendor/samsung/goghspr/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/samsung/goghspr/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/goghspr/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/samsung/goghspr/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/samsung/goghspr/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/samsung/goghspr/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/samsung/goghspr/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/samsung/goghspr/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/samsung/goghspr/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/samsung/goghspr/proprietary/lib/libbson.so:system/lib/libbson.so \
    vendor/samsung/goghspr/proprietary/lib/libbt-aptx-4.0.3.so:system/lib/libbt-aptx-4.0.3.so \
    vendor/samsung/goghspr/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/samsung/goghspr/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/samsung/goghspr/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
    vendor/samsung/goghspr/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
    vendor/samsung/goghspr/proprietary/lib/libcneutils.so:system/lib/libcneutils.so \
    vendor/samsung/goghspr/proprietary/lib/libcurl.so:system/lib/libcurl.so \
    vendor/samsung/goghspr/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/samsung/goghspr/proprietary/lib/libdnshostprio.so:system/lib/libdnshostprio.so \
    vendor/samsung/goghspr/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/samsung/goghspr/proprietary/lib/libdrawglfunction.so:system/lib/libdrawglfunction.so \
    vendor/samsung/goghspr/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/samsung/goghspr/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/samsung/goghspr/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/samsung/goghspr/proprietary/lib/libdsucsd.so:system/lib/libdsucsd.so \
    vendor/samsung/goghspr/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/samsung/goghspr/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/samsung/goghspr/proprietary/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/samsung/goghspr/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/samsung/goghspr/proprietary/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/samsung/goghspr/proprietary/lib/libGLESv2_dbg.so:system/lib/libGLESv2_dbg.so \
    vendor/samsung/goghspr/proprietary/lib/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/samsung/goghspr/proprietary/lib/libgps.so:system/lib/libgps.so \
    vendor/samsung/goghspr/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/samsung/goghspr/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/samsung/goghspr/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/samsung/goghspr/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/goghspr/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/samsung/goghspr/proprietary/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
    vendor/samsung/goghspr/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/samsung/goghspr/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/goghspr/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/samsung/goghspr/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/samsung/goghspr/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/samsung/goghspr/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/samsung/goghspr/proprietary/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \
    vendor/samsung/goghspr/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/samsung/goghspr/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/samsung/goghspr/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/samsung/goghspr/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
    vendor/samsung/goghspr/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/goghspr/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/samsung/goghspr/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/samsung/goghspr/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/samsung/goghspr/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    vendor/samsung/goghspr/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
    vendor/samsung/goghspr/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/samsung/goghspr/proprietary/lib/libmmwfdinterface.so:system/lib/libmmwfdinterface.so \
    vendor/samsung/goghspr/proprietary/lib/libmmwfdsinkinterface.so:system/lib/libmmwfdsinkinterface.so \
    vendor/samsung/goghspr/proprietary/lib/libmmwfdsrcinterface.so:system/lib/libmmwfdsrcinterface.so \
    vendor/samsung/goghspr/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/samsung/goghspr/proprietary/lib/libNimsWrap.so:system/lib/libNimsWrap.so \
    vendor/samsung/goghspr/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/goghspr/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
    vendor/samsung/goghspr/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/samsung/goghspr/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/samsung/goghspr/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/samsung/goghspr/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/samsung/goghspr/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/samsung/goghspr/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/samsung/goghspr/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/samsung/goghspr/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/samsung/goghspr/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/samsung/goghspr/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/samsung/goghspr/proprietary/lib/libqsap_sdk.so:system/lib/libqsap_sdk.so \
    vendor/samsung/goghspr/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/samsung/goghspr/proprietary/lib/libquipc_os_api.so:system/lib/libquipc_os_api.so \
    vendor/samsung/goghspr/proprietary/lib/libquipc_ulp_adapter.so:system/lib/libquipc_ulp_adapter.so \
    vendor/samsung/goghspr/proprietary/lib/libQWiFiSoftApCfg.so:system/lib/libQWiFiSoftApCfg.so \
    vendor/samsung/goghspr/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/samsung/goghspr/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/samsung/goghspr/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/samsung/goghspr/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/samsung/goghspr/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/samsung/goghspr/proprietary/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
    vendor/samsung/goghspr/proprietary/lib/libssl.so:system/lib/libssl.so \
    vendor/samsung/goghspr/proprietary/lib/libulp.so:system/lib/libulp.so \
    vendor/samsung/goghspr/proprietary/lib/libulp2.so:system/lib/libulp2.so \
    vendor/samsung/goghspr/proprietary/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    vendor/samsung/goghspr/proprietary/lib/libwfdhdcpcp.so:system/lib/libwfdhdcpcp.so \
    vendor/samsung/goghspr/proprietary/lib/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
    vendor/samsung/goghspr/proprietary/lib/libwfdmmutils.so:system/lib/libwfdmmutils.so \
    vendor/samsung/goghspr/proprietary/lib/libwfdnative.so:system/lib/libwfdnative.so \
    vendor/samsung/goghspr/proprietary/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    vendor/samsung/goghspr/proprietary/lib/libwfdsm.so:system/lib/libwfdsm.so \
    vendor/samsung/goghspr/proprietary/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    vendor/samsung/goghspr/proprietary/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    vendor/samsung/goghspr/proprietary/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    vendor/samsung/goghspr/proprietary/lib/libwifiscanner.so:system/lib/libwifiscanner.so \
    vendor/samsung/goghspr/proprietary/lib/libwiperjni_v02.so:system/lib/libwiperjni_v02.so \
    vendor/samsung/goghspr/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/samsung/goghspr/proprietary/lib/libxt_v02.so:system/lib/libxt_v02.so \
    vendor/samsung/goghspr/proprietary/lib/modules/prima/prima_wlan.ko:system/lib/modules/prima/prima_wlan.ko \
    vendor/samsung/goghspr/proprietary/lib/pp_proc_plugin.so:system/lib/pp_proc_plugin.so \
    vendor/samsung/goghspr/proprietary/lib/qnet-plugin.so:system/lib/qnet-plugin.so \
    vendor/samsung/goghspr/proprietary/lib/tcp-connections.so:system/lib/tcp-connections.so
    
PRODUCT_COPY_FILES += \
    vendor/samsung/goghspr/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so
    
PRODUCT_COPY_FILES += \
    vendor/samsung/goghspr/proprietary/etc/OperatorPolicy.xml:system/etc/OperatorPolicy.xml \
#    vendor/samsung/goghspr/proprietary/etc/quipc.conf:system/etc/quipc.conf \
    vendor/samsung/goghspr/proprietary/etc/thermald.conf:system/etc/thermald.conf \
    vendor/samsung/goghspr/proprietary/etc/UserPolicy.xml:system/etc/UserPolicy.xml \
	vendor/samsung/goghspr/proprietary/etc/DxHDCP.cfg:system/etc/DxHDCP.cfg

 #   vendor/samsung/goghspr/proprietary/bin/netd:system/bin/netd \
